In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)

### element-wise addition, subtraction, multiplication and division

In [3]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.1400766  10.50089351 10.98811347 10.12578689 10.31610535]
 [10.18698387 10.77346802 10.98660173 10.89019729 10.69884323]
 [10.37554332 10.36318766 10.22539624 10.12884716 10.34133959]
 [10.00916831 10.40264897 10.57834082 10.83988764 10.99363865]
 [10.01677755 10.1578524  10.3583762  10.51121385 10.08735459]]
[[-9.8599234  -9.49910649 -9.01188653 -9.87421311 -9.68389465]
 [-9.81301613 -9.22653198 -9.01339827 -9.10980271 -9.30115677]
 [-9.62445668 -9.63681234 -9.77460376 -9.87115284 -9.65866041]
 [-9.99083169 -9.59735103 -9.42165918 -9.16011236 -9.00636135]
 [-9.98322245 -9.8421476  -9.6416238  -9.48878615 -9.91264541]]
[[1.40076596 5.00893505 9.88113474 1.25786891 3.16105348]
 [1.8698387  7.73468024 9.86601732 8.90197293 6.98843228]
 [3.75543318 3.63187662 2.25396245 1.28847157 3.41339593]
 [0.09168306 4.02648968 5.78340819 8.3988764  9.93638645]
 [0.16777547 1.57852401 3.58376204 5.11213851 0.87354592]]
[[0.01400766 0.05008935 0.09881135 0.01257869 0.03161053]
 [0.01869839 0.0773

In [4]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


### element-wise exponentiation

In [5]:
print(np.exp(arr))

[[1.15036191 1.65019507 2.68616218 1.13404047 1.37177476]
 [1.20560784 2.16726938 2.68210446 2.43561013 2.0114246 ]
 [1.45578215 1.43790567 1.25281904 1.13751625 1.40683091]
 [1.00921046 1.49578173 1.78307753 2.31610672 2.70104476]
 [1.01691908 1.17099334 1.43100387 1.66731384 1.09128357]]


### element-wise logorithm

In [6]:
# natural log
print(np.log(arr))      

[[-1.96556589 -0.69136176 -0.01195774 -2.07316614 -1.15167974]
 [-1.67673292 -0.25687095 -0.01348883 -0.11631216 -0.35832884]
 [-0.97938145 -1.0128356  -1.48989534 -2.0491284  -1.07487742]
 [-4.69200278 -0.90969014 -0.54759193 -0.17448716 -0.00638167]
 [-4.08771377 -1.84609485 -1.026172   -0.67096728 -2.43777967]]


In [7]:
# base 2
print(np.log2(arr))     

[[-2.83571217 -0.99742419 -0.01725137 -2.99094651 -1.66152265]
 [-2.41901427 -0.37058645 -0.01946027 -0.16780298 -0.51695924]
 [-1.41294876 -1.4612129  -2.14946461 -2.95626739 -1.55072033]
 [-6.76912915 -1.31240546 -0.79000817 -0.25173176 -0.00920681]
 [-5.89732439 -2.66335189 -1.48045325 -0.96800117 -3.51697264]]


In [8]:
# base 10
print(np.log10(arr))    

[[-0.85363442 -0.3002546  -0.00519318 -0.90036462 -0.50016816]
 [-0.72819586 -0.11155764 -0.00585813 -0.05051373 -0.15562024]
 [-0.42533996 -0.43986891 -0.64705332 -0.88992516 -0.46681333]
 [-2.03771092 -0.39507341 -0.23781615 -0.07577881 -0.00277153]
 [-1.77527154 -0.80174881 -0.44566084 -0.29139739 -1.05871426]]


### element-wise square root

In [9]:
print(np.sqrt(arr))

[[0.37426808 0.7077383  0.99403897 0.35466448 0.56223247]
 [0.43241632 0.87947031 0.99327828 0.94350267 0.83596844]
 [0.61281589 0.60265053 0.47475914 0.35895286 0.58424275]
 [0.09575127 0.63454627 0.76048722 0.91645384 0.99681425]
 [0.12952817 0.39730643 0.59864531 0.7149922  0.2955581 ]]


### element-wise sine and cosine

In [10]:
print(np.sin(arr))

[[0.13961896 0.48020947 0.83498937 0.12545545 0.31086724]
 [0.18589619 0.69862078 0.83415656 0.77719591 0.64333251]
 [0.36677804 0.35525576 0.2234926  0.12849094 0.3347497 ]
 [0.00916818 0.39185683 0.54663534 0.74456812 0.83801693]
 [0.01677676 0.15719767 0.35075406 0.48923627 0.08724354]]


In [11]:
print(np.cos(arr))

[[0.9902053  0.87715384 0.55026607 0.99209925 0.95045334]
 [0.98256939 0.71549214 0.55152773 0.6292587  0.76558689]
 [0.93030848 0.93476914 0.97470563 0.99171068 0.94230708]
 [0.99995797 0.92002621 0.83737077 0.66754649 0.54564423]
 [0.99985926 0.98756716 0.93646761 0.87215129 0.99618701]]


### sum along a specified axis

In [12]:
# sum along the row
print(np.sum(arr, axis=0))    

[0.72854964 2.19805056 3.13682847 2.49593283 2.43728141]


In [13]:
# sum along the column
print(np.sum(arr, axis=1))    

[2.07097582 3.53609415 1.43431398 2.82368438 1.13157459]


### compute the min and max along a specified axis

In [14]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.00916831 0.1578524  0.22539624 0.12578689 0.08735459]


In [15]:
# calculate max along the column
print(np.max(arr, axis=1))    

[0.98811347 0.98660173 0.37554332 0.99363865 0.51121385]


In [16]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.9936386451958777
0.009168305635023244


### compute the indices of the min and max along a specified axis

In [17]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[3 4 2 0 4]
[2 1 0 1 3]


In [18]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[3 0 3 0 0]
[2 2 0 4 3]


In [19]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

15
19


### compute element-wise min and max of two arrays

In [20]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [21]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.68183193 0.40788865 0.20700125 0.79291829 0.95747632 0.97762183
 0.25926689 0.77857541 0.0142513  0.48231778]
integral:  [1. 7. 3. 7. 3. 4. 1. 0. 8. 8.]


### compute the mean

In [22]:
# compute the overall mean
print(np.mean(arr))

0.4398657164341664


In [23]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[0.14570993 0.43961011 0.62736569 0.49918657 0.48745628]


In [24]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.41419516 0.70721883 0.2868628  0.56473688 0.22631492]


### compute the median

In [25]:
# compute the overall median
print(np.median(arr))

0.36318766202323616


In [26]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.1400766  0.40264897 0.57834082 0.51121385 0.34133959]


In [27]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.31610535 0.77346802 0.34133959 0.57834082 0.1578524 ]


### compute the percentile

In [28]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.05708343 0.53709984 0.92486189]


### compute the standard deviation & variance

In [29]:
# compute the overall standard deviation
print(np.std(arr))

0.3150803398210832


In [30]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.1340342  0.2009033  0.31481033 0.33036037 0.31990549]


In [31]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.31775486 0.27807893 0.09529378 0.3448996  0.18248868]


In [32]:
# compute the overall variance
print(np.var(arr))

0.09927562054176928


In [33]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.01796517 0.04036214 0.09910554 0.10913797 0.10233952]


In [34]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.10096815 0.07732789 0.0090809  0.11895573 0.03330212]


### compute the covariance & correlation

In [35]:
arr = np.random.rand(5,8)

In [36]:
print(np.cov(arr))

[[ 0.11106547  0.03147986  0.00691849  0.00966515 -0.04051229]
 [ 0.03147986  0.07217646 -0.0224185  -0.01060107  0.04182017]
 [ 0.00691849 -0.0224185   0.03087738  0.0325757  -0.03391866]
 [ 0.00966515 -0.01060107  0.0325757   0.08358182 -0.00483402]
 [-0.04051229  0.04182017 -0.03391866 -0.00483402  0.0845634 ]]


In [37]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.39646763]
 [-0.39646763  1.        ]]


### compute cumulative sum & product

In [38]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[0.12257902 0.44963516 0.93690939 0.50339526 0.09153582 0.1252493
  0.79671593 0.13305871]
 [0.35122702 1.1685525  1.6700285  1.12892179 0.80566836 0.48526686
  1.05734129 0.18273644]
 [0.70428489 1.30813837 2.2056579  1.16699546 0.99754531 0.80296417
  1.36653834 0.70944393]
 [1.22862751 1.46052146 3.01392822 1.38412143 1.04367764 1.54444153
  1.50053808 1.0894316 ]
 [1.62258645 2.21817696 3.27579746 2.01766404 1.71431759 2.37488451
  1.5841245  1.22199635]]


In [39]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.12257902 0.57221418 1.50912357 2.01251884 2.10405466 2.22930396
  3.02601989 3.1590786 ]
 [0.228648   0.94756534 1.68068445 2.30621098 3.02034351 3.38036108
  3.64098644 3.69066416]
 [0.35305787 0.49264374 1.02827314 1.06634681 1.25822376 1.57592107
  1.88511812 2.41182561]
 [0.52434262 0.67672571 1.48499602 1.70212199 1.74825433 2.48973169
  2.62373143 3.00371909]
 [0.39395894 1.15161444 1.41348369 2.0470263  2.71766624 3.54810922
  3.63169564 3.76426039]]


In [40]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[1.22579018e-01 4.49635164e-01 9.36909392e-01 5.03395263e-01
  9.15358229e-02 1.25249297e-01 7.96715930e-01 1.33058715e-01]
 [2.80274469e-02 3.23250515e-01 6.86866182e-01 3.14887092e-01
  6.53687091e-02 4.50919467e-02 2.07644377e-01 6.61005432e-03]
 [9.89531085e-03 4.51212043e-02 3.67905720e-01 1.19889060e-02
  1.25427487e-02 1.43255901e-02 6.42030282e-02 3.48156515e-03]
 [5.18853319e-03 6.87570855e-03 2.97367272e-01 2.60310286e-03
  5.78626287e-04 1.06221007e-02 8.60318946e-03 1.32295180e-03]
 [2.04406906e-03 5.20941839e-03 7.78713430e-02 1.64917658e-03
  3.88049900e-04 8.82104898e-03 7.19109747e-04 1.75376778e-04]]


In [41]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[1.22579018e-01 5.51158366e-02 5.16385450e-02 2.59945989e-02
  2.37943700e-03 2.98022811e-04 2.37439521e-04 3.15933975e-05]
 [2.28647998e-01 1.64379010e-01 1.20509394e-01 7.53818230e-02
  5.38326122e-02 1.93806859e-02 5.05109827e-03 2.50927074e-04]
 [3.53057875e-01 4.92818906e-02 2.63968294e-02 1.00502407e-03
  1.92840955e-04 6.12650524e-05 1.89429733e-05 9.97740599e-06]
 [5.24342617e-01 7.99009483e-02 6.45815647e-02 1.40223350e-02
  6.46883057e-04 4.79649141e-04 6.42728628e-05 2.44228948e-05]
 [3.93958944e-01 2.98485161e-01 7.81640836e-02 4.95202775e-02
  3.32102760e-02 2.75792407e-02 2.30524981e-03 3.05594872e-04]]


### element-wise comparison

In [42]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [43]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]
