In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

### ```np.concatenate((a, b), axis=0)```

In [3]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [4]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [5]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [6]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [7]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [8]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [9]:
arr = np.random.rand(6,6)

In [10]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.51928837, 0.75702945, 0.8869501 , 0.06154417, 0.64569548,
        0.80590086],
       [0.23255039, 0.00517894, 0.64068124, 0.60630284, 0.92713505,
        0.28106229],
       [0.89953814, 0.07969817, 0.26337217, 0.48490354, 0.80622842,
        0.80413747]]), array([[0.27453403, 0.60053547, 0.4875841 , 0.5239318 , 0.20048652,
        0.07798728],
       [0.1547374 , 0.40408388, 0.91402697, 0.4308554 , 0.19387303,
        0.18710442],
       [0.64990805, 0.52350193, 0.84937351, 0.29894124, 0.49680501,
        0.39490244]])]


In [11]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.51928837, 0.75702945, 0.8869501 ],
       [0.23255039, 0.00517894, 0.64068124],
       [0.89953814, 0.07969817, 0.26337217],
       [0.27453403, 0.60053547, 0.4875841 ],
       [0.1547374 , 0.40408388, 0.91402697],
       [0.64990805, 0.52350193, 0.84937351]]), array([[0.06154417, 0.64569548, 0.80590086],
       [0.60630284, 0.92713505, 0.28106229],
       [0.48490354, 0.80622842, 0.80413747],
       [0.5239318 , 0.20048652, 0.07798728],
       [0.4308554 , 0.19387303, 0.18710442],
       [0.29894124, 0.49680501, 0.39490244]])]
