In [1]:
import numpy as np

In [2]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

### matrix multiplication

In [3]:
print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[1.10026784 1.11433396 0.98175071 1.26700021 1.55104979]
 [1.0940006  1.07307665 0.84038513 1.05385953 1.21785087]
 [0.76949737 1.17368096 0.92485461 1.28254421 1.02610908]
 [0.63900465 0.60244428 0.42914735 0.50821234 0.57294549]
 [1.00722682 1.18074849 0.9276191  1.29222872 1.24110222]]
[[1.10026784 1.11433396 0.98175071 1.26700021 1.55104979]
 [1.0940006  1.07307665 0.84038513 1.05385953 1.21785087]
 [0.76949737 1.17368096 0.92485461 1.28254421 1.02610908]
 [0.63900465 0.60244428 0.42914735 0.50821234 0.57294549]
 [1.00722682 1.18074849 0.9276191  1.29222872 1.24110222]]
[[1.10026784 1.11433396 0.98175071 1.26700021 1.55104979]
 [1.0940006  1.07307665 0.84038513 1.05385953 1.21785087]
 [0.76949737 1.17368096 0.92485461 1.28254421 1.02610908]
 [0.63900465 0.60244428 0.42914735 0.50821234 0.57294549]
 [1.00722682 1.18074849 0.9276191  1.29222872 1.24110222]]


### QR factorization 

In [4]:
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q)
print(r)

[[-6.53835715e-01  2.33291965e-01 -3.57074535e-02 -5.38308560e-01
  -4.76468874e-01]
 [-2.42242792e-04 -5.45163503e-01 -7.03420324e-01  1.81154409e-01
  -4.18544650e-01]
 [-3.84308530e-01  1.42505489e-01 -5.56538737e-01 -7.10945188e-02
   7.19172680e-01]
 [-7.14601975e-02 -7.56442767e-01  2.86472422e-01 -5.10461772e-01
   2.82931283e-01]
 [-6.47841951e-01 -2.36343266e-01  3.34847743e-01  6.41701896e-01
   2.32020113e-02]]
[[-1.18282515 -0.8364082  -0.66327075 -0.69216038 -0.97195962]
 [ 0.         -1.15793259 -1.24897415 -0.92951405 -0.35732941]
 [ 0.          0.         -0.17521874 -0.52730589  0.09692846]
 [ 0.          0.          0.         -0.41565421 -0.55504233]
 [ 0.          0.          0.          0.         -0.05539149]]


### singular value decomposition (SVD)

In [5]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.1858383  -0.44768685  0.26520971 -0.83226926 -0.04508099]
 [-0.46190162 -0.56201704 -0.52187852  0.25879148 -0.3625652 ]
 [-0.39642822  0.64382825 -0.03651425 -0.23644237 -0.60917286]
 [-0.67095834  0.21580474 -0.14452912 -0.04984266  0.69272669]
 [-0.38048731 -0.15042218  0.796922    0.42657421 -0.12470905]]
[2.79105013 0.9836999  0.50106868 0.11554473 0.0221589 ]
[[-0.33572721 -0.44255026 -0.47615774 -0.47299328 -0.49090495]
 [ 0.56112103 -0.16466495 -0.67535796  0.44916698 -0.01301092]
 [ 0.04340784  0.22671839  0.25514165  0.38774276 -0.85514491]
 [-0.70439911  0.38742958 -0.4083843   0.41178188  0.13182627]
 [ 0.27270512  0.75863813 -0.29204526 -0.50459649 -0.10095573]]


### compute eigen values

In [6]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.48064968+0.j         -0.41757515+0.j         -0.13899379+0.23852809j
 -0.13899379-0.23852809j  0.05118784+0.j        ]


### eigen value decomposition

In [7]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.19805937  0.61608675  0.43195095 -0.34221224 -0.09799391]
[[-0.49982166 -0.55133474 -0.04186109  0.11089852 -0.08280435]
 [-0.51361595 -0.34009678  0.46876523  0.28549728  0.24082054]
 [-0.36290473  0.44182138 -0.16042123  0.44828343  0.28954837]
 [-0.4464288  -0.53994161  0.84250038 -0.75350746 -0.92055593]
 [-0.39418073  0.30597568 -0.20727985 -0.37075773 -0.06234922]]


### compute the trace & determinant

In [8]:
# notice this is not a function in linalg!!!
print(np.trace(arr))    

2.805890916961743


In [9]:
print(np.linalg.det(arr))

0.019615996110603617


### calculate the inverse/psedo-inverse of a matrix

In [10]:
arr = np.random.rand(5,5)

In [11]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[ 0.65076911 -0.43662078 -2.32688276  1.27125883  0.92255849]
 [-0.78946668  1.64649295  2.43062998  0.00610988 -2.73656234]
 [-1.01473513  0.34693783  2.65980874  0.06021902 -1.22365935]
 [-0.17798532 -0.00656649 -2.12487269  0.44880176  1.87354721]
 [ 1.97710832 -0.84845124  0.82479329 -2.19258879  1.26432108]]


In [12]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[ 0.65076911 -0.43662078 -2.32688276  1.27125883  0.92255849]
 [-0.78946668  1.64649295  2.43062998  0.00610988 -2.73656234]
 [-1.01473513  0.34693783  2.65980874  0.06021902 -1.22365935]
 [-0.17798532 -0.00656649 -2.12487269  0.44880176  1.87354721]
 [ 1.97710832 -0.84845124  0.82479329 -2.19258879  1.26432108]]


### solve a linear system

In [13]:
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

[ 2.49470701 -3.862963    1.7811461   4.5972067   0.30583593]


In [14]:
# calculate the least-squares solution of a linear system
y = [1,2,3,4,5]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
print(solution)
print(residuals)
print(rank)
print(singular)

[ 2.49470701 -3.862963    1.7811461   4.5972067   0.30583593]
[]
5
[2.22813681 1.06403841 0.77357806 0.27404705 0.16042712]


/var/folders/b1/551fs6bn4q9cs5f6pcg_7t0h0000gn/T/ipykernel_9523/727852024.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
